### ISSUE TITLE
请问群晖docker容器如何配置环境？

### ISSUE THREAD

**Issue by leonxis** [wahyd4/aria2-ariang-x-docker-compose#10]
你好，群晖的docker里下载了你的ariang，但是容器配置参数不知道具体怎么弄，页面里总是未连接，能麻烦详细讲一下容器配置吗
看运行日志是都正常的。卷只配置了/data文件夹，端口映射了相同的，但是就是无法连接、
谢谢！

**Comment by wahyd4** [comment]
需要：
* 映射 80 和 6800 两个内部端口。6800 是 aria2 的端口，显示未连接，可能主要是这个端口没有映射
* 需要volume 目录。
如果还是搞不定，你可以把你自己的配置贴出来。
你可以参见 #9
