### ISSUE TITLE
ERROR: pull access denied for afian/filerun, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by zhengdechang** [wahyd4/aria2-ariang-x-docker-compose#104]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
---
## 中文版

请提供详细的信息！

* 你的CPU 平台是什么？ X64还是ARM？
* 使用的是什么应用作为文件管理？
* 你使用的什么命令来执行这个程序？
* docker 容器是否都是正常运行？
* 日志输出是什么样子的？
* 是否可以重现这个问题？ 如何重新？
* 使用的操作系统以及Docker 版本
* （可选）应用截图或者日志截图

**Comment by zhengdechang** [comment]
Does afian/filerun image require permissions to be pulled

**Comment by wahyd4** [comment]
Thanks for reporting this issue, looks like this docker image has been moved private or deleted, I will try to update it over the weekend.

**Comment by wahyd4** [comment]
Hi there, after checking `filerun` website and I found that they have switched their product into the paid model and are no longer free. That's why the docker image disappeared.
So I can't maintain filerun docker-compose file anymore.

**Comment by zhengdechang** [comment]
thanks
