### ISSUE TITLE
[typoes / README] 文档错字

### ISSUE THREAD

**Issue by rosuH** [wahyd4/aria2-ariang-x-docker-compose#11]
下图中应该的端口应该是 `8000` 吧？

![image](https://user-images.githubusercontent.com/15865017/30304598-db444fb0-97a0-11e7-9ce6-bccef74eb141.png)

**Comment by wahyd4** [comment]
多谢提醒。今天有空的时候我改下。
rosu <notifications@github.com>于2017年9月12日 周二上午9:58写道：
