### ISSUE TITLE
弄一个自启动脚本

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#12]
新手不知道应该怎么写

**Comment by wahyd4** [comment]
童鞋已经很简单了啊。安装 docker 自动不了。

1. 安装 docker， docker-compose
2. clone 代码
3. cd 到你需要的目录，docker-compose up -d

**Comment by ptsa** [comment]
童靴 我说的是开机自启动, 不是自动安装

**Comment by wahyd4** [comment]
哦，这个我稍后修改下 docker-compose 文件应该就可以实现了

ptsa <notifications@github.com>于2017年9月15日周五 上午10:20写道：

**Comment by wahyd4** [comment]
现在 docker 镜像在被意外停掉后就会自动重启了。前提是 docker 进程还在，比如，主机被强制重启。那么 docker 镜像会自动重启。
使用： 
```bash
docker-compose stop
git pull
docker-compose up -d
```

**Comment by lgh06** [comment]
提醒。  
CentOS7。应该在安装完Docker后执行这两句：  
```  
systemctl start docker.service
systemctl enable docker.service  
```  
然后再docker-compose
（通过docker官网的script方式安装的docker，没有自动启动）
