### ISSUE TITLE
nextcloud 不能删除外部的aria2下载的文件的原因可能是所有者不同

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#13]
nextcloud 不能删除外部的aria2下载的文件的原因可能是所有者不同
能不能让他们属于同一个所有者?
![qq 20170915101016](https://user-images.githubusercontent.com/4506307/30463389-187bea82-99fe-11e7-8dae-f6793ee6c1ed.png)

**Comment by wahyd4** [comment]
这个只能你自己设置，或者你去 nextcloud 社区找找有没有相应的办法，这个和本项目没有关系哦

**Comment by lqzhgood** [comment]
我全新安装的 centos7 ，安装完也是这样。
root 用户运行的 docker。但是 winscp 查看 nextcloud 所有者总是这个 991 。我并没有创建这个用户啊。

**Comment by wahyd4** [comment]
Docker里面的用户和外面的用户是不一样的。简单讲你可以把docker看成虚拟机，是一种隔离

**Comment by wahyd4** [comment]
@lqzhgood  这个应该是 Nextcloud 的一个 bug，把你需要添加的用户使用 `chown -R 991 目录名称`， 赋予给991，即可以上传文件了， 请参考最新版本的 readme 文档
