### ISSUE TITLE
aria2 好像不会保存配置?

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#14]
aria2 好像不会保存配置?
docker-compose stop
docker-compose up -d 
之后 下载记录和设置都没有了

**Comment by wahyd4** [comment]
这个是aria2 或者 ariaNg 的问题哈。和我们这个项目无关，你可以到相关项目去提 issue.

**Comment by ptsa** [comment]
我发现都找不到配置文件和下载记录的临时文件
nextcloud倒是找到了   /data/nextcloud

**Comment by wahyd4** [comment]
```bash
bash-4.3# ls
conf
bash-4.3# cd conf/
bash-4.3# ls
aria2.conf  aria2c.sh   key
bash-4.3# pwd
/root/conf
```
aria2.conf 即是配置文件,打开该文件，dir 配置这是文件下载目录
```
#文件保存路径, 默认为当前启动位置
# dir=/user-files/superuser/
dir=/var/www
```

**Comment by ptsa** [comment]
没有 conf 文件夹 /root/下面
![qq 20170915111454](https://user-images.githubusercontent.com/4506307/30464947-1649c1fe-9a07-11e7-9c94-b76b00f1d678.png)

**Comment by wahyd4** [comment]
把你的 wahyd4/aria2-ariang 镜像 tag 发出来看看

**Comment by ptsa** [comment]
怎么操作? 我是今天刚接触docker的

**Comment by wahyd4** [comment]
... 建议你先去了解下 docker 的基本知识。
配置文件是在 docker 容器里面，而不是在你自己电脑上。
 `docker images` 就能看到了

**Comment by ptsa** [comment]
{"Repositories":{"hello-world":{"hello-world:latest":"sha256:05a3bd381fc2470695a35f230afefd7bf978b566253199c4ae5cc96fafa29b37","hello-world@sha256:1f1404e9ea1a6665e3664626c5d2cda76cf90a4df50cfee16aab1a78f58a3f95":"sha256:05a3bd381fc2470695a35f230afefd7bf978b566253199c4ae5cc96fafa29b37"},"wahyd4/aria2-ariang":{"wahyd4/aria2-ariang:caddy-nextcloud":"sha256:b844ceb6aba871fd120ed204bb60b45552ba92f6a157d3ecfe442adb725307f2","wahyd4/aria2-ariang@sha256:c84c1e774326fd91aa20fa5d3d69ba68fc8717ffdb7ba07e5dc02e1dd70820de":"sha256:b844ceb6aba871fd120ed204bb60b45552ba92f6a157d3ecfe442adb725307f2"},"wonderfall/nextcloud":{"wonderfall/nextcloud:latest":"sha256:c3869fa3a020ea2450f22dc253b263f508f7fcb48af94b1e9e34c02551d91053","wonderfall/nextcloud@sha256:903e9129d52c935d9fe80e1264b641f42ade2f1a1c08c12f39ce7f950ed5ff1c":"sha256:c3869fa3a020ea2450f22dc253b263f508f7fcb48af94b1e9e34c02551d91053"}}}

**Comment by ptsa** [comment]
对了 我有用阿里云的 docker 加速器

**Comment by wahyd4** [comment]
```bash
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
wahyd4/aria2-ariang               caddy-nextcloud     b844ceb6aba8        10 days ago         65MB
wonderfall/nextcloud              latest              c3869fa3a020        12 days ago         300MB
```

我刚已经确认都是有的。你用阿里云 docker 加速也没有关系。
想要了解更多的还是先看看 docker 基本知识吧，http://wiki.jikexueyuan.com/project/docker-technology-and-combat/

我先吧这个 issue 关掉了。
