### ISSUE TITLE
刚刚 aria2 不能保存配置的问题的原因

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#15]
刚刚 aria2 不能保存配置的问题的原因
应该就是 root 下没有 
/root/conf/key The folder which stored Aria2 SSL certificate and key file. Notice: The certificate file should be named aria2.crt and the key file should be named aria2.key

应该就是没有这个的原因?
这个要怎么处理 按你帮助里面的流程 弄的

**Comment by wahyd4** [comment]
首先本地不能启用 https,
然后请仔细阅读： https://github.com/wahyd4/aria2-ariang-x-docker-compose/blob/master/enable-ssl.md
最后请不要随意开 issue！！
