### ISSUE TITLE
aria2 的问题没有解决

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#16]
刚才我复制的内容有错
我没有启用https

你说的:
bash-4.3# ls
conf
bash-4.3# cd conf/
bash-4.3# ls
aria2.conf  aria2c.sh   key
bash-4.3# pwd
/root/conf
aria2.conf 即是配置文件,打开该文件，dir 配置这是文件下载目录

#文件保存路径, 默认为当前启动位置
# dir=/user-files/superuser/
dir=/var/www

我意思是没有 /root/conf 文件夹 
aria2.conf  aria2c.sh   key   这3个文件也没有

我是按你介绍的步奏弄的

我的意思是你那边没有我说的问题码?
不要随意开issues  那么qq群或者tg群这类交流的地方有吗?
且我问的也不算特别基础吧?

是不是你的镜像 缺少了配置文件映射?

**Comment by wahyd4** [comment]
你要进到 docker 镜像里面才能看到配置文件，docker exec -it <docker 镜像的 id>

**Comment by ptsa** [comment]
的确是我不懂, 进入以后的确有, 
vi 编辑中文不显示,估计是我系统的问题
然后我建议能不能 映射 在主机,上, 方便备份和修改?
你那边同样也有不能保存 和 重启以后丢失的问题吗?

**Comment by wahyd4** [comment]
暂时不考虑映射 aria2配置文件的问题。因为这个配置修改的需求很低。

没有不能保存配置的问题。 他通过图形界面 Aria2Ng 来配置都是自动保存的。重启后不能丢失配置。只要浏览器没有清空缓存。这些限制是 Aria2Ng 的。

**Comment by ptsa** [comment]
Aria2Ng 里下载磁链 没有速度 
所以 我加bt-tracker

模拟服务升级(或者重启)
docker-compose stop # 将 docker 镜像暂时关掉
git pull origin master # 获取最近代码
docker-compose up -d # 运行最新版本的镜像

下载的任务丢失
bt-tracker丢失


重复下载磁链+添加bt-tracker
然后用 reboot
docker-compose up -d
启动后
下载任务 和 bt-tracker  也是丢失

**Comment by wahyd4** [comment]
@ptsa 多谢提的这个 issue
找到原因了，是因为我提供的 docker 镜像里面缺少相关配置，可以在 <https://github.com/wahyd4/aria2-ariang-docker/blob/master/caddy/conf/aria2.conf> 看到。
```bash
## 进度保存相关 ##
# 从会话文件中读取下载任务
input-file=/root/conf/aria2.session
# 在Aria2退出时保存`错误/未完成`的下载任务到会话文件
save-session=/root/conf/aria2.session
# 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
save-session-interval=10

```
* 请使用 docker-compose stop 先停止docker 容器，
* 然后手动删除本地的老版本镜像： wahyd4/aria2-ariang  (注意选对 tag 哦)
使用 docker rmi -f <镜像 id> 进行删除
* 或者使用 docker pull  wahyd4/aria2-ariang:<相应的tag> 来手动覆盖老版本镜像
* 最后 docker-compose up -d 即可。

Aria2 只会保存和重新加载没有下载完成的任务，下载完成的任务不会保存。
