### ISSUE TITLE
80  443 端口占用问题

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#17]
ERROR: for nextcloud_aria2_1  Cannot start service aria2: driver failed programming external connectivity on endpoint nextcloud_aria2_1 (fa260c77e779b968dafa5d61cba9ce8f44b3802e1a5307fe8c62279a44ea5dd9): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for aria2  Cannot start service aria2: driver failed programming external connectivity on endpoint nextcloud_aria2_1 (fa260c77e779b968dafa5d61cba9ce8f44b3802e1a5307fe8c62279a44ea5dd9): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

能不能监测到端口被占用的话  自动换其他端口?

**Comment by wahyd4** [comment]
这个做不到哦，需要你自己在 docker-compose.yml 手动指定对外暴露的端口

**Comment by ptsa** [comment]
应该怎么写? 对了 见一下 更新日志 写一下

**Comment by wahyd4** [comment]
```bash
aria2:
  image: wahyd4/aria2-ariang:filerun
  links:
    - web:file-manager
  ports:
    - "8000:80" #将此处8000 改为 80端口
    - "6800:6800"
  volumes_from:
    - web
```

**Comment by ptsa** [comment]
找到了  知道怎么处理了
