### ISSUE TITLE
aria2 管理显示不正常 

### ISSUE THREAD

**Issue by ptsa** [wahyd4/aria2-ariang-x-docker-compose#18]
Refused to execute script from 'http://192.168.1.129:8000/js/aria-ng-4a60d788ec.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

aria2 管理显示不正常 

version: '2'

services:
  nextcloud:
    image: wonderfall/nextcloud
    volumes:
      - /data/nextcloud:/data
      - /data:/user-files
    restart: always
  aria2:
    image: wahyd4/aria2-ariang:caddy-nextcloud
    ports:
      - "8000:80"
      - "6800:6800"
      - "83:443"
    volumes_from:
      - nextcloud
    # volumes:
    #   - /some_folder:/root/conf/key
    environment:
      - DOMAIN=:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    links:
      - nextcloud:file-manager
    restart: always

**Comment by wahyd4** [comment]
8000 端口是 nextcloud 使用的。还访问 ariaNg 应该是你的 `http://ip:8000/aria2/`

**Comment by ptsa** [comment]
![1w](https://user-images.githubusercontent.com/4506307/30530186-2ce0fd98-9c77-11e7-96bc-f946e4283571.JPG)
http://ip:8000/aria2/ 就是这样访问的
会不会和我安装的时候 端口没改 后来改有关?
nextcloud  正常访问

![2s](https://user-images.githubusercontent.com/4506307/30530213-6c07eaea-9c77-11e7-8ccc-3ac930a3cd6c.JPG)
后面我改过端口 并重启了

**Comment by wahyd4** [comment]
地址里面 /aria2/ 必须要有/ ，readme 里面说得清清楚楚啊

ptsa <notifications@github.com>于2017年9月18日周一 下午1:44写道：

**Comment by ptsa** [comment]
抱歉,这个问题没注意到,习惯不加了.
你配置文件里 bt服务器地址(bt-tracker) 这个还是没设置码?
发现还是不能保存

**Comment by wahyd4** [comment]
可以在浏览器里面设置和保存啊，但是那个是保存在浏览器localstorage里面的。你一清理缓存就会被清空。
切换浏览器也需要宠幸设置一遍。这个都是因为 AriaNg 是这样做的。
![image](https://user-images.githubusercontent.com/836576/30531941-036bf23e-9c17-11e7-98fc-d27ac17fe1cd.png)

配置文件里面是没有添加默认的服务器地址，因为我也不知道有哪些可用用的 bt-tracker 服务器，如果你有可以提供下，我后面更新进去。

**Comment by ptsa** [comment]
我是这样操作的,浏览器 添加 之后 重启 浏览器 刷新 之后就没有了

https://github.com/ngosang/trackerslist

这里 是别人收集的 你可以加一下


现在磁链没有这个的话 很难下载

**Comment by ptsa** [comment]
https://github.com/ngosang/trackerslist

这里 是别人收集的 你可以加一下

**Comment by wahyd4** [comment]
我试了，刷新之后，记录还在哦。
你不要使用隐私模式来浏览网站

**Comment by ptsa** [comment]
不是隐私模式,.我在研究看看

**Comment by wahyd4** [comment]
已经添加了推荐的 bt-tracker 服务器了，请更新对应的： wahyd4/aria2-ariang 镜像获取该功能
