### ISSUE TITLE
建议加个 nginx , 使用80端口

### ISSUE THREAD

**Issue by junbaor** [wahyd4/aria2-ariang-x-docker-compose#2]
看到端口不太舒服，最好上个 https

**Comment by wahyd4** [comment]
代理到一个端口这个需求可以有。然后添加 HTTPS 这个功能需要去调研下，开了另外一个 issue。

**Comment by wahyd4** [comment]
@junbaor 请参考最新 README 文档，新版只使用一个 8000 端口，如果你希望使用80端口。请修改docker-compose 文件中的一个参数即可。还是请参看 README 文档。
https://github.com/wahyd4/aria2-ariang-x-docker-compose#升级

**Comment by wahyd4** [comment]
@junbaor  已经支持该配置了哈，参见： https://github.com/wahyd4/aria2-ariang-x-docker-compose#高级特性
