### ISSUE TITLE
更改端口号后不生效 监控的还是8000

### ISSUE THREAD

**Issue by ziisp** [wahyd4/aria2-ariang-x-docker-compose#20]
更改/root/aria2-ariang-x-docker-compose/nextcloud/docker-compose.yml文件里的端口号为80，但是没有生效，重启容器不行，重启主机也不行。
version: '2'

services:
  nextcloud:
    image: wonderfall/nextcloud
    volumes:
      - /data/nextcloud:/data
      - /data:/user-files
    restart: always
  aria2:
    image: wahyd4/aria2-ariang:caddy-nextcloud
    ports:
      - "80:80"
      - "6800:6800"
      - "443:443"
    volumes_from:
      - nextcloud
    # volumes:
    #   - /some_folder:/root/conf/key
    environment:
      - DOMAIN=:80
      # - SSL=true
      # - RPC_SECRET=Hello
       - ARIA2_USER=admin
       - ARIA2_PWD=admin
       - ENABLE_AUTH=true
    links:
      - nextcloud:file-manager
    restart: always

**Comment by wahyd4** [comment]
我刚在本地测试了，没有这样的问题啊，是可以正常工作的。
```yaml
ports:
- "80:80" #修改这一行即可
```
你可以通过
docker-compose down 删除容器
docker rmi  <docker 镜像 id> 手动删除镜像
然后再 docker-compose up 重启镜像试试。

**Comment by ziisp** [comment]
使用你这个方法生效了，但是在启用验证验证后，启动容器报错
`ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yml", line 21, column 7
expected <block end>, but found '<block sequence start>'
  in "./docker-compose.yml", line 25, column 8
`
就是验证那两行的错误
`version: '2'

services:
  nextcloud:
    image: wonderfall/nextcloud
    volumes:
      - /data/nextcloud:/data
      - /data:/user-files
    restart: always
  aria2:
    image: wahyd4/aria2-ariang:caddy-nextcloud
    ports:
      - "80:80"
      - "6800:6800"
      - "443:443"
    volumes_from:
      - nextcloud
    # volumes:
    #   - /some_folder:/root/conf/key
    environment:
      - DOMAIN=:80
     # - DOMAIN=cloud.ccer.me
     #  - SSL=true
      # - RPC_SECRET=Hello
       - ARIA2_USER=admin
       - ARIA2_PWD=admin
       - ENABLE_AUTH=true
    links:
      - nextcloud:file-manager
    restart: always


`

**Comment by ziisp** [comment]
并且启用HTTPS也会报出那一行的错误。

**Comment by wahyd4** [comment]
你这个是语法错误哦。你看看25行修改了什么东西吧
ziisp <notifications@github.com>于2017年10月17日 周二下午6:19写道：

**Comment by ziisp** [comment]
可是我是直接取消了配置的注释 并没有改代码啊。求解。

**Comment by wahyd4** [comment]
你的25行是哪一行？

**Comment by ziisp** [comment]
- ARIA2_USER=admin

**Comment by wahyd4** [comment]
问题可能出在，注释的行夹杂在中间！！
environment:
- DOMAIN=:80
# - DOMAIN=cloud.ccer.me
# - SSL=true
# - RPC_SECRET=Hello
- ARIA2_USER=admin
- ARIA2_PWD=admin
- ENABLE_AUTH=true
你试试把注释的那几行暂时删除试试

**Comment by ziisp** [comment]
非常感谢，确实是这个原因。
