### ISSUE TITLE
nextcloud应用页面加载不出来

### ISSUE THREAD

**Issue by xuexiaoao** [wahyd4/aria2-ariang-x-docker-compose#21]
如图，一直在转圈
![image](https://user-images.githubusercontent.com/18185523/33376956-a3e4f208-d54a-11e7-88e4-7b9368b51c36.png)

**Comment by wahyd4** [comment]
在这个页面，右键里面，打开chrome 的调试界面看看报什么错
薛奡 <notifications@github.com>于2017年11月30日 周四00:17写道：

**Comment by xuexiaoao** [comment]
调试界面没有报错，就是一直请求数据，不过打开nextcloud的日志，发现是请求超时的错误
![image](https://user-images.githubusercontent.com/18185523/33377156-620ff1b0-d54b-11e7-8de9-7df601f76f08.png)
### 刚刚重启了一下主机，又是一直在转圈，不过这次加载出来了。。。。。。

**Comment by wahyd4** [comment]
那这个就是自己网络的问题哦。有可能现在晚上
你的服务器和本机浏览器之间的网络连接太慢了

薛奡 <notifications@github.com>于2017年11月30日 周四00:29写道：
