### ISSUE TITLE
Filerun 管理 aria下载创建文件 的权限问题

### ISSUE THREAD

**Issue by greathappyforest** [wahyd4/aria2-ariang-x-docker-compose#22]
个人比较喜欢用filerun.  设置给data及其以下的所有文件777以后，发现aria下载创建的文件和目录是在root下，文件是644和目录是755，所以www-data不能直接通过网页云端直接管理aria下载好的东西。每次都需要重新给这些文件覆盖777权限才能管理。有没什么更好的办法解决这个问题。

**Comment by wahyd4** [comment]
请考虑使用 root 用户来运行 docker  程序。docker 需要更高的权限
