### ISSUE TITLE
设置aria2下载位置

### ISSUE THREAD

**Issue by ziyitony** [wahyd4/aria2-ariang-x-docker-compose#25]
非常感谢老司机带路，但是我看了一下，不知道如何设置aria2的下载位置，webui设置的下载位置无效。请问aria2的配置文件在哪里，我使用的是nextcloud组合。
进程显示的aria2的配置文件保存在/root/conf/aria2.conf路径，但是我的配置机器上并没有这个路径。请指教，谢谢。

**Comment by wahyd4** [comment]
就在你说的这个路径，只有这个路径！你是需要进入到docker里面去看路径哦，不是本机。

另外设置下载位置，你只需要修改宿主机绑定的位置就好了。请看文档
ziyitony <notifications@github.com>于2017年12月26日 周二下午7:21写道：

**Comment by ziyitony** [comment]
我去试试，非常感谢！

**Comment by ziyitony** [comment]
文档是docker-compose.yml这个文件中的位置吗？

**Comment by wahyd4** [comment]
对，volume 这个字段下
ziyitony <notifications@github.com>于2017年12月26日 周二下午7:40写道：

**Comment by ziyitony** [comment]
哦，我的上帝呀，那真是极好的！
