### ISSUE TITLE
什么系统可以安装哦，文章里都没写，我用的centos7 安装不上

### ISSUE THREAD

**Issue by findwisdom** [wahyd4/aria2-ariang-x-docker-compose#27]
什么系统可以安装哦，文章里都没写，我用的centos7` 安装不上

`[root@apkgm nextcloud]# #安装Docker Compose                                                                    
[root@apkgm nextcloud]#                                                                                      
[root@apkgm nextcloud]# curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`un
ame -s`-`uname -m` -o /usr/local/bin/docker-compose                                                          
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                              
                                 Dload  Upload   Total   Spent    Left  Speed                                
100   617    0   617    0     0   1171      0 --:--:-- --:--:-- --:--:--  1173                               
100 8649k  100 8649k    0     0  3802k      0  0:00:02  0:00:02 --:--:-- 5415k                               
[root@apkgm nextcloud]#                                                                                      
[root@apkgm nextcloud]# chmod +x /usr/local/bin/docker-compose                                               
[root@apkgm nextcloud]# git clone https://github.com/wahyd4/aria2-ariang-x-docker-compose.git                
Cloning into 'aria2-ariang-x-docker-compose'...                                                              
remote: Counting objects: 305, done.                                                                         
remote: Total 305 (delta 0), reused 0 (delta 0), pack-reused 305                                             
Receiving objects: 100% (305/305), 676.57 KiB | 0 bytes/s, done.                                             
Resolving deltas: 100% (132/132), done.                                                                      
[root@apkgm nextcloud]#                                                                                      
[root@apkgm nextcloud]# cd aria2-ariang-x-docker-compose/nextcloud                                           
[root@apkgm nextcloud]#                                                                                      
[root@apkgm nextcloud]# docker-compose up -d                                                                 
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?                   
                                                                                                             
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.               
[root@apkgm nextcloud]# Connection closed   `

**Comment by wahyd4** [comment]
本项目和系统无关。
其次看你这个错，你电脑里面没有装docker 和docker compose 哦。这两个东西你在搜索引擎里面可以找到文章讲如何在centos 上面安装的。
