### ISSUE TITLE
老哥，如何在安装有nginx得前提下使用你这个docker 。。。

### ISSUE THREAD

**Issue by Mr-xn** [wahyd4/aria2-ariang-x-docker-compose#28]
老哥，如何在安装有nginx得前提下使用你这个docker 。。。

**Comment by wahyd4** [comment]
单独运行`wahyd4/aria2-ui` 容器即可哦， 然后添加一个 nginx 代理规则给该容器使用即可， 请参考：

https://github.com/wahyd4/aria2-ariang-docker
