### ISSUE TITLE
AriaNg只能显示文字，不能显示图形界面，是什么原因呢？

### ISSUE THREAD

**Issue by ghost** [wahyd4/aria2-ariang-x-docker-compose#29]
从`http://xxx:8000/aria2`进入，AriaNg只能显示文字，不能显示图形界面。caddy代理应该如何设置？是不是压缩比例过大了？

**Comment by wahyd4** [comment]
地址最后一定要带斜杠哦！ 请参考readme
请使用： http://xxx:8000/aria2/
