### ISSUE TITLE
似乎这个docker-compose不支持mac系统

### ISSUE THREAD

**Issue by Wilson-G** [wahyd4/aria2-ariang-x-docker-compose#30]
安装报错

> ERROR: for nextcloud_nextcloud_1  Cannot start service nextcloud: Mounts denied: 
> The paths /data and /data/nextcloud
> are not shared from OS X and are not known to Docker.
> You can configure shared paths from Docker -> Preferences... -> File Sharing.
> See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
> .
> 
> ERROR: for nextcloud  Cannot start service nextcloud: Mounts denied: 
> The paths /data and /data/nextcloud
> are not shared from OS X and are not known to Docker.
> You can configure shared paths from Docker -> Preferences... -> File Sharing.
> See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
> .
> ERROR: Encountered errors while bringing up the project.
> 
没太明白是什么原因，能看一下么

**Comment by wahyd4** [comment]
在 mac docker
的mount目录设置里面，把/data目录添加进去
