### ISSUE TITLE
修改端口为80访问不了了

### ISSUE THREAD

**Issue by qwinwin** [wahyd4/aria2-ariang-x-docker-compose#31]
reboot了下
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

如何启动这个啊，，，小白一个  请大佬指教

**Comment by wahyd4** [comment]
运行本项目，需要确保docker已经处于运行状态。 service docker start

**Comment by qwinwin** [comment]
多谢
