### ISSUE TITLE
大佬nextcloud的权限问题能给个简单教程嘛

### ISSUE THREAD

**Issue by qwinwin** [wahyd4/aria2-ariang-x-docker-compose#32]

**Comment by qwinwin** [comment]
翻了issues看到很多人都有这个问题但是好像没有解决方案。。不晓得如何给docker权限

**Comment by wahyd4** [comment]
请简要描述下，你遇到这种情况使用的用户，一般这种问题出现在你是使用非root用户运行docker

**Comment by qwinwin** [comment]
是root用户啊  然后service docker start启动docker

**Comment by qwinwin** [comment]
centos7系统 命令都是root执行的

**Comment by wahyd4** [comment]
那你遇到的具体错误消息是什么呢？

**Comment by qwinwin** [comment]
就是nextcloud里提示没有权限上传或创建文件
用aria2下载的那些文件

**Comment by wahyd4** [comment]
我平时都是在ubuntu和mac测试的，最近我找机会重现下这个问题吧

**Comment by qwinwin** [comment]
好的

**Comment by wahyd4** [comment]
@Shirooooo  经过测试，确实有这个问题，请参考这里的更新（或者直接再次打开 readme）来进行配置：
https://github.com/wahyd4/aria2-ariang-x-docker-compose/commit/b57db8b0db54b63d793657e2b6020505398c0463

**Comment by qwinwin** [comment]
好的辛苦啦
