### ISSUE TITLE
请问大佬如何把Aria2和nextcloud的网站目录映射到本地

### ISSUE THREAD

**Issue by qbyyy** [wahyd4/aria2-ariang-x-docker-compose#34]
本机里用apache2搭建了两个站点而且绑定了域名，现在这个docker不知道如何绑定域名了。。。所以想直接把docker里的网站目录映射出来，通过apache配置文件绑定域名。
不知道大佬觉得可行吗，或者有更好的办法吗？

**Comment by wahyd4** [comment]
不直接绑定任何域名到aria2-docker 上，通过ip（localhost 应该就行） 和端口的形式访问。
然后在apache 配置中将该ip 加端口绑定到 域名下即可。

**Comment by qbyyy** [comment]
还是有点不会，我的是ubuntu的，加载了proxy那几个mod。
```
ln -s ./../mods-available/proxy_connect.load ./proxy_connect.load
ln -s ./../mods-available/proxy_http.load ./proxy_http.load
ln -s ./../mods-available/proxy_ftp.conf ./proxy_ftp.conf
ln -s ./../mods-available/proxy_ftp.load ./proxy_ftp.load
ln -s ./../mods-available/proxy.conf ./proxy.conf
ln -s ./../mods-available/proxy.load ./proxy.load
```
```
<VirtualHost *:80>

    ServerName  down.xxx.cn
    ServerAlias down.xxx.cn
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://***.***.***.***:60080/
    ProxyPassReverse / http://***.***.***.***::60080/

</VirtualHost>
```
还是不行，不知道哪里出错了，大佬您那有没有教程

**Comment by wahyd4** [comment]
apache 我不太了解，你需要自己去其他地方需找帮助。但是既然你已经绑定了两个其他的站点，那么这第三个站点其实配置是类似的。

**Comment by qbyyy** [comment]
那两个是基于域名区分的站点，这次是基于端口来区分，我搜到的教程都是在配置文件里加了网站目录的，因为没有目录，所以不知道怎么办

**Comment by wahyd4** [comment]
Apache reverse proxy: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html 

不行就是用Nginx 吧，更加流行的方案

**Comment by qbyyy** [comment]
哈哈 我通过apache2的反向代理成功了，感谢大佬提供思路~
