### ISSUE TITLE
Mac运行Docker App 后，再执行 docker-compose up -d，提示端口号被占用

### ISSUE THREAD

**Issue by li8911255** [wahyd4/aria2-ariang-x-docker-compose#36]
ERROR: for h5ai_aria2_1  Cannot start service aria2: b'driver failed programming external connectivity on endpoint h5ai_aria2_1 (5536bd10311cf127974361c8f472b3c8c95440511b3cbc80c256001df100f4e3): Bind for 0.0.0.0:8000 failed: port is already allocated'

ERROR: for aria2  Cannot start service aria2: b'driver failed programming external connectivity on endpoint h5ai_aria2_1 (5536bd10311cf127974361c8f472b3c8c95440511b3cbc80c256001df100f4e3): Bind for 0.0.0.0:8000 failed: port is already allocated'
ERROR: Encountered errors while bringing up the project.

**Comment by wahyd4** [comment]
你有没有执行`docker ps` 看看是否已经有aria2 的容器存在了？
