### ISSUE TITLE
nextcloud下删除文件的问题

### ISSUE THREAD

**Issue by zxjack** [wahyd4/aria2-ariang-x-docker-compose#38]
我用aria2下载的文件，拉回本地之后要删除。在nextcloud中无法直接删除。能解决吗？我现在都是ssh登录服务器中用命令删除。

**Comment by wahyd4** [comment]
@zxjack 请获取最新代码，按照升级流程重新试试！ <https://github.com/wahyd4/aria2-ariang-x-docker-compose#%E5%8D%87%E7%BA%A7>

主要是替换了 nextcloud 的 docker 镜像，最新版使用了官方的镜像，我自己进行了测试，已经可以正常删除外部存储中的文件了。

**Comment by zxjack** [comment]
我按照您说的进行了升级，目前nextcloud的版本是Nextcloud 13.0.4，是否还需要设置其他地方。直接增加了外部存储后还是不能进行删除，显示没有权限。

**Comment by wahyd4** [comment]
你的 docker 是否是使用 root 用户运行的？如果不是可能会出现问题

**Comment by zxjack** [comment]
我的docker是用root的运行的。

**Comment by wahyd4** [comment]
你能帖一些你运行 docker ps 的结果吧，我看看你是否用的是最新的镜像

**Comment by zxjack** [comment]
5b205f5589b7        nextcloud                                       "/entrypoint.sh apac…"   2 minutes ago       Up 2 minutes        80/tcp                                                            root_nextcloud_1
上面的是docker ps输出的nextcloud的结果。
我用的docker-compose.yml中相关的脚本如下：
nextcloud:
     image: nextcloud
     volumes:
          - /data/nextcloud:/var/www/html
          - /data:/user-files
     restart: always
   aria2:
     image: wahyd4/aria2-ui:nextcloud
     restart: always
     container_name: aria2
     volumes_from:
          - nextcloud
     ports:
          - "8000:80"
          - "6800:6800"
     expose:
          - "80"
     environment:
          - VIRTUAL_HOST=###
          - VIRTUAL_PORT=80
          - LETSENCRYPT_HOST=###
          - LETSENCRYPT_EMAIL=###@###
          - DOMAIN=:80  
     volumes_from:
          - nextcloud
     links:
          - nextcloud:file-manager

**Comment by wahyd4** [comment]
你的配置看起来没啥问题，我也刚刚重新在本地重现了下，还是可以使用的。你看你能不能换和电脑或者环境重现下试试吧

**Comment by zxjack** [comment]
en，我估计是我用的google的服务器的问题，我用的debian，我换个环境试试看吧。多谢

**Comment by wahyd4** [comment]
也许和`/data` 目录有关，你尝试把这个目录换成当前用户下的某个目录

**Comment by zxjack** [comment]
我现在用的是root用户，我用root用户新建一个目录试试看。

**Comment by zxjack** [comment]
搞定了，不是权限的问题，我重新修改了docker-compose.yml，
```
volumes:
    - /data/nextcloud:data:rw
    - /data:/user-files:rw
    - /abc:/abc:rw
```
这样我这边就ok了，可以删除文件了。多谢你的帮助
