### ISSUE TITLE
通过访问ip:8000进入nextcloud提示 502 Bad Gateway

### ISSUE THREAD

**Issue by cwj57740** [wahyd4/aria2-ariang-x-docker-compose#39]
可以正常进入http://ip:8000/aria2，没有其他额外的设置

**Comment by wahyd4** [comment]
Nextcloud启动时间较长，第一次启动大概需要3分钟左右，请确保足够的时间。然后你可以docker logs一下nextcloud容器的日志看看

访问地址/aria2/后面需要加上斜线

**Comment by cwj57740** [comment]
@wahyd4 感谢你的回复。启动容器后使用 docker logs nextcloud_nextcloud_1后看到以下信息，之后再查看也没有任何变化：
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Jul 24 01:15:56.556038 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.1.20 configured -- resuming normal operations
[Tue Jul 24 01:15:56.556597 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by wahyd4** [comment]
看起来没有异常出现，容器也是正在运行中。 你是试过几次都是这样吗？

**Comment by cwj57740** [comment]
对，尝试后h5ai则可以正常显示出界面

**Comment by wahyd4** [comment]
你不是用的nextcloud吗，怎么又是h5ai

**Comment by cwj57740** [comment]
就是换h5ai可以用，nextcloud则会502

**Comment by cwj57740** [comment]
@wahyd4 我通过更改nextcloud的docker镜像为wonderfall/nextcloud就没有问题了

**Comment by wahyd4** [comment]
那你应该是升级了代码 git pull过,  但是你没有清空缓存，因为我最近刚刚切换到官方的docker 镜像，然后官方的镜像和wonderfall
的镜像暴露的端口不一样，所以我对Caddy的配置文件也修改过，你可以按照readme 里面升级相关的命令，重新运行。

**Comment by hiBlunt** [comment]
我在使用nextclou版本，git pull更新之后也遇到了502问题，按照readme文件中升级命令全部执行一遍之后仍然是502.我将images和container全部删除之后重新使用docker-compose问题依旧存在。请问删除缓存的命令是什么呢？
ps：现在使用的是filerun，还是觉得nextcloud好用。谢谢你的工作~

**Comment by wahyd4** [comment]
```bash
docker-compose down 
```
就可以清理掉缓存，但是要重新下载最新的镜像还是需要用
```bash
docker-compose pull
```
我刚在 Mac 上 Vultr 上面的 Ubuntu 上面试了，`library/nextcloud`的镜像确实启动很慢，大概需要3-5分钟左右，在这之前你访问会得到502，几分钟后日志里面会出现类似下面的日志:
```bash
nextcloud_1  | Finished code integrity check
nextcloud_1  | Update successful
nextcloud_1  | Turned off maintenance mode
nextcloud_1  | Reset log level
nextcloud_1  | The following apps have beed disabled:
```
就说明正常启动了，可以正常访问，我再比较下其他镜像，看看能不能解决这个问题吧

**Comment by hiBlunt** [comment]
![image](https://user-images.githubusercontent.com/21240907/44204345-c05ee680-a184-11e8-99a2-4c9528c8f115.png)
依旧是502.根据上面给出的命令和https://stackoverflow.com/questions/32612650/how-to-get-docker-compose-to-always-re-create-containers-from-fresh-images中的docker-compose down,docker-compose pull, docker-compose up --force-recreat -d依旧无效。。。

**Comment by wahyd4** [comment]
不知你的服务器是不是在国内，我发现这个 nextcloud 容器启动的时候会下载一个40多 M 的文件，下载完成后才会启动，我的不在国内

**Comment by hiBlunt** [comment]
我使用的是阿里云华北二区的服务器。我刚才试着使用docker rm,docker rmi命令删除了容器和镜像，然后重新安装，问题还是没有解决。这个问题可以在我的另一台独服上复现。

**Comment by wahyd4** [comment]
@lhuang001  请pull 最新代码，然后使用`docker-compose pull` 更新镜像后，再次运行。现在启动时间应该会更快一点，在国内。但是也要1-3分钟所有。耐心等待一下，在这之前你是会碰到502 错误

**Comment by hiBlunt** [comment]
好的，谢谢
