### ISSUE TITLE
aria2能支持需要登陆才能操作，不然放着不怎么安全额

### ISSUE THREAD

**Issue by inmyfree** [wahyd4/aria2-ariang-x-docker-compose#4]

**Comment by wahyd4** [comment]
aria2 和 ariaNg 本身不提供这样的功能。作为docker-compose，我能做的仅仅是在 nginx 里面提供这样的功能。

但是很难做到通过配置来选择开启和关闭安全认证，而且让用户设置自己的密码，这一步也必须手动完成。

因此，在没有找到更好，更自动化的方式之前。暂时会吧这个 issue 放到一边。如果你需要，可以执行进行 aria2-ariang 容器进行设置：
```bash
docker exec -it 该容器 ID bash #进入容器命令行, 然后做你相关操作

```

请参考： 
* https://www.digitalocean.com/community/tutorials/how-to-set-up-basic-http-authentication-with-nginx-on-ubuntu-14-04
* http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html

**Comment by fantasylidong** [comment]
不是直接改aria2的配置文件就行了么。
难道改了之后docker用不了了？

**Comment by wahyd4** [comment]
那你可以在ui里面修改试试啊。
fantasylidong <notifications@github.com>于2017年8月25日 周五下午5:48写道：

**Comment by gowinder** [comment]
ariang不支持用户名密码确实不方便，请问用什么办法手动设置？

**Comment by wahyd4** [comment]
@gowinder 暂时只能通过手动配置 nginx 来实现auth 验证哦。目前 ariaNg 是通过 nginx 来运行的。

**Comment by wahyd4** [comment]
@gowinder @inmyfree @fantasylidong 已经支持该项配置了哈，是 caddy 的 basic auth,参见： https://github.com/wahyd4/aria2-ariang-x-docker-compose#高级特性
