### ISSUE TITLE
如何自定义h5ai/aria2管理的文件夹？

### ISSUE THREAD

**Issue by sunmd01** [wahyd4/aria2-ariang-x-docker-compose#40]
RT，因为我的数据大部分都是在/home/user/data/目录下，我想把h5ai展示的目录设置为这个目录？
还有如何设置aria2下载目录路径？

**Comment by wahyd4** [comment]
你说的`/home/user/data` 是宿主机的目录吧？ 如果是的话，你只需要将该目录mount 到h5ai的显示目录`/var/www`即可
```yaml
volumes:
      - /home/user/data:/var/www
```
