### ISSUE TITLE
aria2下载磁力链接速度为0，如何添加tracker或dht文件

### ISSUE THREAD

**Issue by hiBlunt** [wahyd4/aria2-ariang-x-docker-compose#41]
aria2下载磁力链接速度为0，如何添加tracker或dht文件？还有如果想自定义aria2的参数，在哪里可以找到aria2配置文件呢？

**Comment by wahyd4** [comment]
在ariang，里面可以通过UI设置。aria2的文件也是可以覆盖更新的，请看文档，和查看docker-compose.yml

**Comment by hiBlunt** [comment]
好的，谢谢啦，终于可以下载磁力链接了。
