### ISSUE TITLE
无法显示

### ISSUE THREAD

**Issue by chinkaysin** [wahyd4/aria2-ariang-x-docker-compose#43]
ubuntu 16.04
安装nextcloud版本
前序安装环境都正常 docker运行后

ip:8000/aria2 无法显示或打开慢
ip:8000 502错误

**Comment by wahyd4** [comment]
没有3000端口暴露，nextcloud启动需要3分钟左右，请耐心等待，如果docker日志里面没有错误日志，等待就好了，之前有个类似的issue有详细提到，请搜索查看

**Comment by chinkaysin** [comment]
等待后nextcloud正常，但aria2一直不正常，aliyun新加坡和online.net部署均出现此问题

**Comment by wahyd4** [comment]
aria2，哪里不正常？网址最后添加 / 了吗？

**Comment by chinkaysin** [comment]
加/后正常，捂脸，感谢大佬
