### ISSUE TITLE
为什么aria2下载的文件都是root权限

### ISSUE THREAD

**Issue by channelsray** [wahyd4/aria2-ariang-x-docker-compose#44]
![default](https://user-images.githubusercontent.com/20846732/44299447-8fb7b200-a328-11e8-9d51-d784e5111a6d.PNG)

**Comment by wahyd4** [comment]
因为这个镜像里面执行程序的用户就是root用户。

**Comment by channelsray** [comment]
这样我aria2下载的文件只有可读的权限了，没法删除

**Comment by wahyd4** [comment]
容器外面的用户和容器里面的用户是不一样的。容器里面可以使用非root用户，但是并不能使用你当前宿主机的用户（非root)。

我不认为在你不使用root用户运行docker的情况下，我改变了容器内用户为非root用户能解决问题。

建议目前使用root用户来运行docker本身

或者你也可以尝试修改docker-compose.yml，为 aria2 service添加privileged属性，以获取 root 权限


aria2:
  image: wahyd4/aria2-ui:nextcloud
  privileged: true

**Comment by channelsray** [comment]
确实是使用root用户登录的，只不过是aria2下载的文件是root才有写的权限，但是nextcloud只有991的权限，使得aria2下载的文件只有读没有写的权限

**Comment by wahyd4** [comment]
不太理解你说的`991`的问题，本程序中的 nextcloud 也是使用 root 用户的。而且经过之前的修复 https://github.com/wahyd4/aria2-ariang-x-docker-compose/issues/38  

使用 root 用户不能删除文件的权限的问题应该已经解决了。

**Comment by channelsray** [comment]
我这里nextcloud 运行和文件夹权限就变成991了。。
![default](https://user-images.githubusercontent.com/20846732/44300029-cabee300-a332-11e8-9902-1659f0a5de0a.PNG)

**Comment by wahyd4** [comment]
你这个 nextcloud 是什么目录？ 991 是用户 ID 和用户组 ID 吧，不是权限。 是你宿主机自己设置的，还是被容器创建的？

**Comment by channelsray** [comment]
我查看了以下#38用的是官方的nextCloud，#39又切换回去了

**Comment by wahyd4** [comment]
是，现在是用的第三方做的镜像，因为官方镜像，在启动时，需要下载几十M的文件，导致在国内很可能下载启动不成功。

但是这个和权限没啥关系，主要是之前我没有对目录手动添加rw权限导致的

**Comment by channelsray** [comment]
nextcloud 是被容器创建的目录，创建开始是root权限，进入网页之后更新为991权限，

**Comment by wahyd4** [comment]
刚查了 Nextcloud 镜像的文档, 991是他们默认设置的用户ID 和用户组 ID， 是可以通过环境变量覆盖的。修改 docker-compose.yml 中，nextcloud 镜像里面的参数即可
https://github.com/Wonderfall/docker-nextcloud#environment-variables

```yaml
environment:
   - UID=
   - GID=
```
就可以手动绑定，让容器和宿主机运行于同样的用户了。
我后期也会更新代码让 Aria2 镜像也能支持绑定 UID 和 GID

**Comment by channelsray** [comment]
对，我也查了，但是nextClout还需要修改三个地方，他默认禁止root
第一个：修改/php/etc/php-fpm.comf
![image](https://user-images.githubusercontent.com/20846732/44304827-e14c5500-a399-11e8-9f70-d94398c44a6b.png)
添加user和group为root的选项
第二个： 修改/etc/s6.d/php/run
![image](https://user-images.githubusercontent.com/20846732/44304837-1658a780-a39a-11e8-8e34-ae33a0c3ebba.png)
加上 -R 允许root 启动
第三个： 修改/nginx/conf/nginx.conf
![image](https://user-images.githubusercontent.com/20846732/44304841-51f37180-a39a-11e8-91eb-4ebcaa498bf0.png)
添加 user root root;修改为root启动

**Comment by oceanwave72** [comment]
> 对，我也查了，但是nextClout还需要修改三个地方，他默认禁止root
> 第一个：修改/php/etc/php-fpm.comf
> ![image](https://user-images.githubusercontent.com/20846732/44304827-e14c5500-a399-11e8-9f70-d94398c44a6b.png)
> 添加user和group为root的选项
> 第二个： 修改/etc/s6.d/php/run
> ![image](https://user-images.githubusercontent.com/20846732/44304837-1658a780-a39a-11e8-8e34-ae33a0c3ebba.png)
> 加上 -R 允许root 启动
> 第三个： 修改/nginx/conf/nginx.conf
> ![image](https://user-images.githubusercontent.com/20846732/44304841-51f37180-a39a-11e8-91eb-4ebcaa498bf0.png)
> 添加 user root root;修改为root启动

这些文件怎么我都找不到。。。
