### ISSUE TITLE
Aria2 状态是未连接

### ISSUE THREAD

**Issue by KimTae-mu** [wahyd4/aria2-ariang-x-docker-compose#45]

**Comment by wahyd4** [comment]
请提供更多的信息！

* 使用的是什么应用作为文件管理？
* docker 容器是否都是正常运行？
* 日志输出是什么样子的？
* （可选）应用截图

**Comment by KimTae-mu** [comment]
nextcloud
均正常运行

![image](https://user-images.githubusercontent.com/23636296/44380910-7a1cd500-a540-11e8-87b5-3e64f4afa234.png)

**Comment by KimTae-mu** [comment]
好了,我忘记添加安全规则了,6800的端口.谢谢!!!
