### ISSUE TITLE
不兼容arm

### ISSUE THREAD

**Issue by GaryH4** [wahyd4/aria2-ariang-x-docker-compose#47]
standard_init_linux.go:190: exec user process caused "exec format error"
google了一番发现是架构不兼容(https://forums.docker.com/t/standard-init-linux-go-190-exec-user-process-caused-exec-format-error/49368)

设备：rock64 
OS: openmediavault  (debian 9)

如果是各类pi的用户，参见此repo
https://github.com/nextcloud/nextcloudpi

**Comment by wahyd4** [comment]
这类问题的话，估计我也处理不了哦，🤣

**Comment by GaryH4** [comment]
建议在readme.md加上说明（以及上面那个repo页面）
（我在我的板子上折腾了好久，起初是docker一直开不了，换了系统之后docker能跑了，然后发现并不兼容）

**Comment by wahyd4** [comment]
这个可以有。主要我拥有的设备有限不能一一测试各种系统和平台。
我想问下，是因为nextcloud docker image 在arm 上运行不了？ 还是啥的错误？

**Comment by GaryH4** [comment]
您所提供的docker image大概是x86架构的（？）
docker log:
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by wahyd4** [comment]
这上面这个错误应该是因为那个go 程序编译的时候不是按照arm 架构编译的。但是我还是不知道这个错误是来自于哪一个docker-image?

**Comment by GaryH4** [comment]
我也不知道啊……就按您的步骤编译的……
（我还没看出来这docker是怎么安装的、源码从哪拖来的……）

**Comment by wahyd4** [comment]
这个项目是不需要编译的，docker images都是用的现成的，只是涉及到镜像的编排。

你是在执行哪一步，或者哪条命令的时候出错的？

**Comment by GaryH4** [comment]
docker-compose up -d
等了半小时，网页还是开不了
然后docker logs，全是error

或许arm的docker image名字不一样？
比如 nextcloudpi ？

**Comment by wahyd4** [comment]
你直接使用 `docker-compose up`，让程序在前台运行，看看哪个image 爆出的错误。
另外你需要去了解下nextcloudpi 是否提供了docker 镜像，这个不一定有。

**Comment by GaryH4** [comment]
我试一试
nextcloudpi提供了docker镜像

**Comment by GaryH4** [comment]
```
Gary@rock64:~/aria2-ariang-x-docker-compose/nextcloud$  sudo docker-compose up
nextcloud_nextcloud_1 is up-to-date
Recreating nextcloud_aria2_1 ... done
Attaching to nextcloud_nextcloud_1, nextcloud_aria2_1
aria2_1      | standard_init_linux.go:190: exec user process caused "exec format error"
nextcloud_1  | standard_init_linux.go:190: exec user process caused "exec format error"
nextcloud_1  | standard_init_linux.go:190: exec user process caused "exec format error"
```

**Comment by wahyd4** [comment]
我编写的`aria2-ui` docker image 里面用到了caddy 是go 程序，是不兼容arm 的，
然后本项目用到的`nextcloud`似乎也用到了go 程序也是不兼容arm 的。

**Comment by GaryH4** [comment]
用nextcloudpi可以运行

```
sudo mkdir nextcloudpi
cd nextcloudpi
sudo wget -c https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/docker-compose-nc-armhf.yml
sudo mv docker-compose-nc-armhf.yml docker-compose.yml
sudo docker-compose up -d
```

**Comment by wahyd4** [comment]
你是说，nextcloud 和ariang UI 界面都可以正常打开？

**Comment by GaryH4** [comment]
Initializing NextCloudPi for the first time

Please wait...

**Comment by GaryH4** [comment]
但是少一个程序
nextcloud_1  | /etc/services-enabled.d/020nextcloud: line 59: ncc: command not found
ncc: command not found
百度了一下没有什么思路
apt-get install ncc 也不是

**Comment by wahyd4** [comment]
在这里想看看有多少人需要运行arm 的镜像呢？ 如果不少人都需要的话，我会考虑发布的，大家来回复或者表情加一下？

**Comment by wahyd4** [comment]
Now the standalone Docker image for aria2c + filemanager supports ARM CPUs, which means you can run it on Raspberry Pi platform, please go to https://cloud.docker.com/repository/docker/wahyd4/aria2-ui/tags choose the correct accordingly.
🍻

By the way, the docker-compose version like Nextcloud tag one still doesn't support ARM CPUs, if you guys really that feature then we can discuss that later on.
