### ISSUE TITLE
nextcloud下删除文件的问题 Pro

### ISSUE THREAD

**Issue by GlodenBoy** [wahyd4/aria2-ariang-x-docker-compose#51]
#38  同样是这个问题，但是无法彻底解决，首先 目录只要是归属ROOT 就只有下载权限，但是aria下载的都是ROOT，手动将文件归属全部改成991后即可删除。

请问有什么一劳永逸的办法。。。

**Comment by wahyd4** [comment]
没有一劳永逸的办法，因为 NextCloud 使用了991 作为容器内的UID，这个很奇怪，通常镜像一般不会这样做。可以参考这里修改 NextCloud 镜像的 `UID`和 `GID`： https://github.com/wahyd4/aria2-ariang-x-docker-compose/issues/44#issuecomment-414089103

**Comment by GlodenBoy** [comment]
> 没有一劳永逸的办法，因为 NextCloud 使用了991 作为容器内的UID，这个很奇怪，通常镜像一般不会这样做。可以参考这里修改 NextCloud 镜像的 `UID`和 `GID`： [#44 (comment)](https://github.com/wahyd4/aria2-ariang-x-docker-compose/issues/44#issuecomment-414089103)

#44  这个方法解决成功了，多谢。

**Comment by wahyd4** [comment]
I am pretty sure #58 has solved this issue, please have a look at that
