### ISSUE TITLE
Plex无法访问

### ISSUE THREAD

**Issue by ruinny** [wahyd4/aria2-ariang-x-docker-compose#53]
Plex一直显示找不到服务器，我记着默认不允许远程连接来着，这个怎么修改？

**Comment by wahyd4** [comment]
请发截图出来，只有文字我不知道是什么原因，同时也可以把aria2c那个docker容器的日志发出来，帮助查找问题。

**Comment by wahyd4** [comment]
Due to no detailed description, logs and images attached, close this now.
