### ISSUE TITLE
nextcloud版本有没有和ocDownloader整合的docker镜像方案

### ISSUE THREAD

**Issue by star7th** [wahyd4/aria2-ariang-x-docker-compose#54]
如果整合了ocDownloader，那么就不再需要ariang了。
可以参考下：https://www.freehao123.com/oneinstack-nextcloud-aria2-ocdownloader/
注意，ocDownloader不支持最新版的nextcloud14 .需要安装nextcloud13

**Comment by wahyd4** [comment]
Ocdownloader 只是nextcloud一个插件而已，自行安装即可。

**Comment by star7th** [comment]
我现在正自己手动安装ing，打算写成个shell自动脚本，一键安装。
从用户角度里看，不用跳转到不同url里去操作，纯一个界面管理/下载文件，体验好很多。

**Comment by wahyd4** [comment]
Aria2还有chrome插件，可以把百度云盘的视频导出链接下载，我比较常用
