### ISSUE TITLE
如何连接Mysql数据库？

### ISSUE THREAD

**Issue by QFP-ZJT** [wahyd4/aria2-ariang-x-docker-compose#56]
我想让nextcloud配置是有Mysql数据库，应该如何配置呢？ 在程序初始化的时候没有数据库设置的入口。

**Comment by wahyd4** [comment]
Please refer the readme page of the Nextcloud docker image we used https://hub.docker.com/r/wonderfall/nextcloud/. 

According to that page, the quick answer is you can have several environment variables set
   > DB_TYPE : database type (sqlite3, mysql or pgsql) (default : sqlite3)
DB_NAME : name of database (default : none)
DB_USER : username for database (default : none)
DB_PASSWORD : password for database user (default : none)
DB_HOST : database host (default : none)

But for this project, we won't bind any specific databases, you can choose what you like.
