### ISSUE TITLE
总是显示 restarting

### ISSUE THREAD

**Issue by hahaxo** [wahyd4/aria2-ariang-x-docker-compose#57]
pi@raspberrypi:~ $ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                          PORTS               NAMES
1e13747979b0        wahyd4/aria2-ui:h5ai   "/bin/sh /root/conf/…"   14 minutes ago      Restarting (1) 48 seconds ago                       h5ai_aria2_1
ef06ba6443d6        bixidock/h5ai          "/usr/local/bin/star…"   15 minutes ago      Restarting (1) 53 seconds ago                       h5ai_h5ai_1

**Comment by hahaxo** [comment]
看了其他的issue，不兼容 raspberry pi

**Comment by wahyd4** [comment]
Now the standalone Docker image for aria2c + filemanager supports ARM CPUs, which means you can run it on Raspberry Pi platform, please go to https://cloud.docker.com/repository/docker/wahyd4/aria2-ui/tags choose the correct accordingly.
🍻
