### ISSUE TITLE
无法创建或写入数据目录/data

### ISSUE THREAD

**Issue by 462428632** [wahyd4/aria2-ariang-x-docker-compose#6]
NextCloud第一次登陆设置密码和数据库时，提示无法创建或写入数据目录/data

**Comment by wahyd4** [comment]
这个是因为你没有权限创建/data目录，请手动创建，使用chmod让你自己有读和写的权限哦。如果你是在windows下运行，请自行修改docker-compose.yml文件里面volumns节点下面的属性，将/data目录，换成你自己想要使用的目录。
462428632 <notifications@github.com>于2017年8月26日 周六上午11:07写道：

**Comment by 462428632** [comment]
你好，
我是刚接触centos,逛vex时候，看到你的文章，家里有台服务器想试着假设个私有云。
根据yml文件配置
/data/nextcloud目录创建成功了，并且给/data目录加了777权限：

但是依旧会有权限提示：

大神，是不是还有其他需要注意的地方呢

**Comment by 462428632** [comment]
解决这个问题了，是服务器selinux的问题
