### ISSUE TITLE
Only expose port of AriaNg

### ISSUE THREAD

**Issue by Remielyzs** [wahyd4/aria2-ariang-x-docker-compose#63]
你好，看了下docker-compose文件，但是发现aria2的部分还是暴露了三个端口出来，请问这个部分有没有办法只暴露ariang的连接端口，把6800和8080都只在容器之间呢。因为之前试验的好像是airang与aira互联的部分，是基于当前网络的情况而不是airang容器的网络情况（比如ng和aria在同一台机器上，内网访问时直接可以填内网的地址，但是外网访问时填内网地址就连不上）

**Comment by wahyd4** [comment]
In short, it's not possible.

Because the AriaNg it's a pure frontend application and only has JavaScript which means all the requests sending from browser not backend. So the Aria ports must be exposed but you can set token to gain more security.
