### ISSUE TITLE
AriaNg: CSS is broken

### ISSUE THREAD

**Issue by doskoi** [wahyd4/aria2-ariang-x-docker-compose#65]
## 中文版

安装readme安装好nextcloud+aira2以后
打开aria2的网页，css无法载入，切换浏览器，重启docker皆是如此。

chrome的console显示
`Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Refused to execute script from 'http://ip:8000/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
aria2:1`

**Comment by wahyd4** [comment]
What's the URL you typed in browser? Please make sure you have the trailing `/` in your URL.

**Comment by doskoi** [comment]
Just as document, http://ip/a <http://up/airs>ria2
It show aria without css load, the links on the page also not working.

Junv <notifications@github.com>于2019年4月28日 周日上午7:24写道：

**Comment by wahyd4** [comment]
Please read readme carefully. This is because you didn't add the trailing / .

**Comment by doskoi** [comment]
It works, but anyway, if I didn't copy the url, I never notice that's a
problem. it's shouln't be.

Junv <notifications@github.com> 于2019年4月28日周日 上午10:13写道：

**Comment by doskoi** [comment]
Thanks

**Comment by WeiYuanStudio** [comment]
@doskoi I also confused by the same problem. LOL

**Comment by wahyd4** [comment]
Hi All, I did some improvement, so now the tailing splash is optional. Please pull the latest version docker image by `docker-compose pull`, then restart the docker compose.
