### ISSUE TITLE
添加自己的文件夹报无效的用户

### ISSUE THREAD

**Issue by kpeng2016** [wahyd4/aria2-ariang-x-docker-compose#66]
[root@localhost mnt]# chown -R www-data udisk
chown: 无效的用户: "www-data"
请问这个怎么处理

**Comment by kpeng2016** [comment]
请问这个怎么处理？

**Comment by wahyd4** [comment]
Could you please let me know where did you run this command? On your host or in the container? In which container?

**Comment by wahyd4** [comment]
Closed due to there are no further updates
