### ISSUE TITLE
希望能提供个带nextcloud的armhf镜像

### ISSUE THREAD

**Issue by LinusJun** [wahyd4/aria2-ariang-x-docker-compose#68]
希望arm32v7 arm64v8也能直接用上镜像

**Comment by wahyd4** [comment]
I can have a look to see whether `nextcloud` or `h5ai` have docker images for ARM, but I actually recommend you to try `wahyd4/aria2-ui` docker image which supports ARM and has all the functions in one docker image. Check it out here https://github.com/wahyd4/aria2-ariang-docker

**Comment by wahyd4** [comment]
Hi @LinusJun , I am pleased to inform you that I have released a new `Nextcloud` compose which allows you to run the application on `arm` based machine. Please checkout readme to see more details https://github.com/wahyd4/aria2-ariang-x-docker-compose#arm-nextcloud.

By the way, if you find this project is helpful, please consider donating through Wechat Pay to support this opensource project, thanks.
