### ISSUE TITLE
对于新手来说

### ISSUE THREAD

**Issue by d5d** [wahyd4/aria2-ariang-x-docker-compose#7]
发表一下心声，能不能搞个一键安装。确实很需要这个离线下载。

**Comment by wahyd4** [comment]
运行 docker-compose 本身只有一步操作了啊，请问是觉得安装 docker 和安装 docker-compose 很麻烦吗？

**Comment by d5d** [comment]
刚试了在centos 安装docker，版本比较旧，没成功，现在安装Ubuntu继续试试。docker-compose可有一键

：）

因为是NAT生的小鸡，请问需要开放那几个端口？
8000
6800

80（能否告知如何修改这个端口，比如8080访问，nat[80端口]这个端口给了web的小鸡）。

**Comment by wahyd4** [comment]
不要使用 系统自带的 yum 和 apt-get 来安装。即使你要用，也应该使用`yum install docker-ce`因为 docker 这个公司开发的版本太快了。而且几个月前将 docker 版本分成了 社区版和企业版。
这里有个阿里云提供的一键安装docker 脚本：
* centos: 
```bash
curl -sSL http://acs-public-mirror.oss-cn-hangzhou.aliyuncs.com/docker-engine/internet | sh -
```
* ubuntu
```bash
curl -sSL http://acs-public-mirror.oss-cn-hangzhou.aliyuncs.com/docker-engine/internet | sh -
```
或者这里有个阿里写的中文文档。
https://yq.aliyun.com/articles/110806

最好的其实还是官方的安装，就那么几步操作。

**Comment by d5d** [comment]
谢谢了，  gogogogo

**Comment by d5d** [comment]
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by wahyd4** [comment]
你这是docker没有成功启动哦
d5d <notifications@github.com>于2017年8月26日 周六下午6:00写道：

**Comment by d5d** [comment]
见笑了，新手。
systemctl start docker

**Comment by wahyd4** [comment]
可以多了解下docker相关的基础知识。会让你平时工作事半功倍的
d5d <notifications@github.com>于2017年8月26日 周六下午6:34写道：
