### ISSUE TITLE
求助，Aria下载失败（Download aborted）

### ISSUE THREAD

**Issue by lywly** [wahyd4/aria2-ariang-x-docker-compose#71]
https://github.com/wahyd4/aria2-ariang-x-docker-compose#%E4%BD%BF%E7%94%A8-filebrowser-%E5%AE%89%E8%A3%85
使用filebrowser安装的方式，将80端口映射到XXXX，在AriaNg设置中将RPC地址更改为XXXX端口了，显示已连接。新建任务时秒出错，报错：发生错误（16）Download aborted. 错误描述：文件创建或删除已有文件失败

**Comment by wahyd4** [comment]
Please follow the issue template to create another issue with enough information!
