### ISSUE TITLE
请问在哪里或者哪个容器里面执行 chown -R www-data <文件夹>

### ISSUE THREAD

**Issue by bebestmaple** [wahyd4/aria2-ariang-x-docker-compose#78]
![image](https://user-images.githubusercontent.com/7425640/66803666-de73d280-ef52-11e9-8786-3f0cd02623bc.png)
docker compose yml文件如下，跟仓库里的一样
1、请问在哪里或者哪个容器里面执行 chown -R www-data <文件夹>
2、请问根据上面的配置我需要给哪些文件夹加权限

**Comment by wahyd4** [comment]
It's been described very clear:
 `在宿主机上执行命令 sudo chown -R www-data <abc> #<>这里是你需要修改的目录, 让Nextcloud 有权限读写、管理文件`

The full version document is here https://github.com/wahyd4/aria2-ariang-x-docker-compose/tree/master/nextcloud

**Comment by bebestmaple** [comment]
It MEANs I need to create a new user named `www-data` in host cause I just see user `www-data` in container nextcloud ? 
From the yaml file,If the nextcloud volums is `/docker/aria2-ariang-x-docker-compose/nextcloud/data:/data`,Then commod is `chown -R  www-data   ./data`

**Comment by bebestmaple** [comment]
Must add commond 
```
- PUID=1000 # bind custom linux user id
- PGID=1000 # bind custom linux group id
```
bind my host user?
Then run` chown -R <bind user> <folder>`
Is that right?
