### ISSUE TITLE
使用 Nextcloud 安装完成后有问题

### ISSUE THREAD

**Issue by x2nbit** [wahyd4/aria2-ariang-x-docker-compose#8]
使用 Nextcloud 安装完成后，Nextcloud的管理界面能打开，也能正常使用，但是无法打开AriaNg： http://xxxxx:8000/aria2，这是为何？

**Comment by x2nbit** [comment]
重启后后打开了，奇怪。。。

**Comment by wahyd4** [comment]
我在本地试了下，http://xxx:8000/aria2 访问不了，会被重定向到一个不存在的网址，

用 http://xxx:8000/aria2/ 这样就是可以的。唯一区别就是最后的 `/`
