### ISSUE TITLE
用户权限问题

### ISSUE THREAD

**Issue by FormatToday** [wahyd4/aria2-ariang-x-docker-compose#82]
能否指定docker运行时的用户或者用户组，这样aria+nextcloud就不需额外配置了。
或者指定docker容器内执行命令的用户不为root，统一为www-data

**Comment by FormatToday** [comment]
https://yeasy.gitbooks.io/docker_practice/image/dockerfile/user.html
我好想找到了一篇文章，不知道有没有用

**Comment by wahyd4** [comment]
For the first question, the answer is no. There is no way of doing this.
For the second one, due to the Nextcloud is not made me, I can't change it. Furthermore, the nextcloud cloud docker image is pretty complex, it's not easy to manage in a simple way.

**Comment by FormatToday** [comment]
Can it be possible by  modifying the aria image?

**Comment by FormatToday** [comment]
make the aria  run by 'www-data' in container

**Comment by wahyd4** [comment]
The user id and group id matter, not because of the username.

**Comment by FormatToday** [comment]
Get it,thank you anyway.
