### ISSUE TITLE
nextcloud 外部存储 有问题

### ISSUE THREAD

**Issue by hrbhot** [wahyd4/aria2-ariang-x-docker-compose#84]
需要手动进入容器
docker exec -it "容器id" sh
apt-get update
apt-get install smbclient
apt-get install libsmbclient-dev
pecl install smbclient

**Comment by wahyd4** [comment]
Hi @hrbhot, Sorry for the late response. I think it's an issue of the Nextcloud image, not this repo. 
Besides, I don't think the issue you mention by any configurations. So I will close it now.

**Comment by wahyd4** [comment]
But please feel free to make any pull request if you have any ideas.
