### ISSUE TITLE
404 Site my.domain.com is not served on this interface

### ISSUE THREAD

**Issue by Drshu** [wahyd4/aria2-ariang-x-docker-compose#86]
**Describe the bug**
After I used it for a period of time, this prompt suddenly appeared, and then I can no longer use it. Even if I reinstall the system and Docker, it did not solve the problem.

**To Reproduce**
I will get this prompt whether you visit domain.com ​​or domain.com/ui/ . I guess there is something wrong with Caddy's configuration.

**Screenshots**
[![Q7CGge.md.png](https://s2.ax1x.com/2019/12/18/Q7CGge.md.png)](https://imgchr.com/i/Q7CGge)

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04.6

**Comment by wahyd4** [comment]
Have you checked the logs of the container? 

Giving a running container, there is no way to change the configuration of that container. I reckon this might because the container has stopped already.

**Comment by Drshu** [comment]
Thanks for your reply.
I tried to use `docker logs ID` to output the logs. And I got this result 
```
Initializing nextcloud 17.0.1.1 ...
Initializing finished
New nextcloud instance
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
[Wed Dec 18 04:22:19.543809 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.12 configured -- resuming normal operations
[Wed Dec 18 04:22:19.545328 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```
But I used the same configuration before and it worked well.

**Comment by wahyd4** [comment]
The logs looks fine, can you access just through IP?

**Comment by Drshu** [comment]
There are same result but the domain change to IP address.

**Comment by wahyd4** [comment]
Which exact type of docker-compose file you are using, 
Below is an example when you request a URL which doesn't exist on the application, the web server I used should return a 404 error message like below. At the same time, you should expect some logs pop up from the container.

![image](https://user-images.githubusercontent.com/836576/71058944-9a50b880-21b5-11ea-851d-a0c50ed1b12c.png)

Looking at your container, I think you might have another container which took over the port belong this application. So make sure all of other container don't use the same port.

**Comment by Drshu** [comment]
Well, I think everything is fine. The result of  `docker ps` :
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                      NAMES
9aa8542adb79        wahyd4/aria2-ui:nextcloud   "./start.sh"             2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nextcloud_aria2_1
647c70a09a81        nextcloud:latest            "/entrypoint.sh apac…"   2 hours ago         Up 2 hours          80/tcp                                     nextcloud_nextcloud_1
```
The first one is ariaNG and the second is Nextcloud I think

**Comment by wahyd4** [comment]
You didn't answer my question, please check logs for `wahyd4/aria2-ui:nextcloud`, when you get 404 in your browser, you should expect some error logs coming out.

Before that, I reckon you stop the application and update the docker images by `docker-compose pull`,  then restart the application again.

**Comment by Drshu** [comment]
There are mess of  `aria2c.1 | ` in the log and did not have any update when I visit the page. Before `aria2c.1 | `, the last log record is `Serialized session to '/app/conf/aria2.session' successfully.`

**Comment by wahyd4** [comment]
I am pretty sure you are not accessing the correct service. You are hitting some other service.

**Comment by Drshu** [comment]
Oh, you're right dude. I think the browser cache is the reason of this issue. Thanks for your help.

**Comment by AdobeFan16** [comment]
This happened to hackedonlinegames.com too, that is, a flash games website and I wonder when it will be up again
![Website down](https://github.com/wahyd4/aria2-ariang-x-docker-compose/assets/156944958/7d8987a9-3c79-4290-826f-2714753d6242)
