### ISSUE TITLE
nextcloud外部存储问题

### ISSUE THREAD

**Issue by GeorgeRudd** [wahyd4/aria2-ariang-x-docker-compose#89]
根本看不懂.... /abc/abc 是什么意思....到底要不要加啊

**Comment by wahyd4** [comment]
**It means you can mount any other folders if you like, it's totally optional!!!**

For instance, if you want to a music files folder:

```bash
- /home/someuser/music:/music
```

Then in `nextcloud` you can add another local drive folder which located in `/music`
