### ISSUE TITLE
希望能出一个单一容器版本的，这样就可以在群晖等各种NAS中跑了，因为群晖自带的docker不支持compose

### ISSUE THREAD

**Issue by goxofy** [wahyd4/aria2-ariang-x-docker-compose#9]

**Comment by wahyd4** [comment]
有 Aria2 + AriaNg 的 docker 镜像。这样就可以图形化的下载bt 和磁力链接了。然后使用 volume 参数把下载目录映射到群晖的某个真实目录。
这样使用群晖自带的文件查看或者 视频播放器就可以播放了啊。你看看这个<https://github.com/wahyd4/aria2-ariang-docker>
有什么问题可以在下面提出来，我帮你解决

**Comment by leonxis** [comment]
你好，群晖的docker里下载了你的ariang，但是容器配置参数不知道具体怎么弄，页面里总是未连接，能麻烦详细讲一下容器配置吗
看运行日志是都正常的。卷只配置了/data文件夹，端口映射了相同的，但是就是无法连接、
谢谢！

**Comment by goxofy** [comment]
好像也可以，谢谢

**Comment by goxofy** [comment]
https://github.com/wahyd4/aria2-ariang-docker

你这个Dockerfile有点问题， 

ENV DOMAIN=localhost:80

改为

ENV DOMAIN=0.0.0.0:80

否则caddy只监听 localhost和127.0.0.1，并不适合跑Nas

就不提request了

我自己直接在群晖docker里另开了一个bash把caddyfile改了写死了0.0.0.0:80，还是建议Dockerfile改一下

**Comment by wahyd4** [comment]
多谢提醒，已经修改。请 pull 最新镜像吧！
```bash

docker pull wahyd4/aria2-ariang

```

**Comment by wahyd4** [comment]
@goxofy  救你刚刚那个问题，即使你不升级镜像，在运行时通过设置环境变量来覆盖`ENV DOMAIN` 效果也是一样的，而不需要手动去修改 docker 容器。

**Comment by goxofy** [comment]
@wahyd4 嗯这个明白
