### ISSUE TITLE
大佬有没有空做一个nextcloud+aria2+plex的？

### ISSUE THREAD

**Issue by MrMu666** [wahyd4/aria2-ariang-x-docker-compose#91]
大佬有没有空做一个nextcloud+aria2+plex的？

**Comment by wahyd4** [comment]
You don't have to have plex in the same compose file, you just need to run a plex container as share the same media files folder then it's enough.

You can find an example of plex docker/docker-compose here <https://hub.docker.com/r/linuxserver/plex/>

**Comment by MrMu666** [comment]
ok, thank you
