### ISSUE TITLE
完全没有速度啊

### ISSUE THREAD

**Issue by liililiu** [wahyd4/aria2-ariang-x-docker-compose#92]
![image](https://user-images.githubusercontent.com/34448876/90961891-8bf23380-e4de-11ea-97e7-442d65001820.png)

完全下载不动，一点速度没有
用的File Browser平台的镜像

**Comment by wahyd4** [comment]
The file downloading speed depends on your torrents  and the source. You
can try to download some popular resources.

**Comment by liililiu** [comment]
和下载的资源是没有关系的，这一点我已经测试并已确认。

**Comment by wahyd4** [comment]
Do you mean this compose file https://github.com/wahyd4/aria2-ariang-x-docker-compose/blob/master/plex-filebrowser/docker-compose.yml ?

If not, can you paste the commands you use to run?

**Comment by wahyd4** [comment]
Hi @liililiu , I have verified the docker image `wahyd4/aria2-ui` by using it with command `  docker run -d --name aria2-ui -p 80:80 wahyd4/aria2-ui`. And it works fine.
The torrent file I used you can find it at https://www.raspberrypi.org/downloads/raspberry-pi-os/

**Comment by wahyd4** [comment]
I assume this has been solved since there is no further update provided.
