### ISSUE TITLE
PLEX 在debug 模式下运行

### ISSUE THREAD

**Issue by yulinfeng000** [wahyd4/aria2-ariang-x-docker-compose#93]
**Describe the bug**
使用docker-compose logs 显示了很多plex的没什么用的 log

**To Reproduce**
使用 filebrowser 的docker compose 文件启动
1. cd *where-your-docker-compose-file-place*
2. docker-compose logs

**Screenshots**
![image](https://user-images.githubusercontent.com/44149505/91627660-6cca3900-e9eb-11ea-9e4d-f8758b22a623.png)

能把log等级默认改成info吗

**Comment by wahyd4** [comment]
Hi @yulinfeng000,  I am happy to accept your suggestion.

There are two ways to solve this:

* From web console
* Update the Plex docker image env configurations. You can check out more details here https://github.com/spritsail/plex-media-server

If you can make a pull request to solve this, that would be great, would you?

**Comment by yulinfeng000** [comment]
yes

**Comment by wahyd4** [comment]
@yulinfeng000  Thanks for your contribution.
Closed by https://github.com/wahyd4/aria2-ariang-x-docker-compose/pull/94
