### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sylaryang** [wahyd4/aria2-ariang-x-docker-compose#95]
Status: Downloaded newer image for wahyd4/aria2-ui:nextcloud-arm32
Creating nextcloud_nextcloud_1 ... done
Creating nextcloud_aria2_1     ... done
Attaching to nextcloud_nextcloud_1, nextcloud_aria2_1
nextcloud_1  | standard_init_linux.go:211: exec user process caused "exec format error"
aria2_1      | standard_init_linux.go:211: exec user process caused "exec format error"
nextcloud_nextcloud_1 exited with code 1
nextcloud_aria2_1 exited with code 1

百度了一下，可能是执行脚本没有加#!bin/bash

不知道是不是这样的。

**Comment by wahyd4** [comment]
This is because you didn't choose the proper CPU platform.

I can see you are using arm32, but what CPU are you running against?

**Comment by sylaryang** [comment]
amlogic S905D, the phnicomm N1 box.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/23307894/92984113-8040ce00-f4da-11ea-82f6-a95c520e9e50.png">

**Comment by wahyd4** [comment]
I think you need to find out what's the CPU platform, arm32 or arm64 or
x64, and then choose the proper tag accordingly.

Kind regards,
Junwei Zhao

**Comment by wahyd4** [comment]
I assume this has bee solved as there is no further feedback provided.
